import mongoose from "mongoose";
import User from '../models/user.model.js';
const listingSchema=new mongoose.Schema(
    {
      name:
      {
        type:String,
        required:true
      },
      description:
      {
        type:String,
        required:true
      },
      address:
      {
        type:String,
        required:true
      },
      sell:
      {
        type:Boolean
      },
      rent:
      {
        type:Boolean
      },
      parking:
      {
        type:Boolean
      },
      furnished:
      {
        type:Boolean
      },
      offer:
      {
        type:Boolean
      },
      bed:
      {
        type:Number,
        required:true
      },
      bath:
      {
        type:Number,
        required:true
      },
      regular:
      {
        type:Number,
        required:true
      },
      discount:
      {
        type:Number
      },
       list:[
        {
           url:
           {
             type:String,
             required:true
           },
           public_id:
           {
              type:String,
             required:true
           }
        }
    ],
    id:
    {
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
    }
    },
    {timestamps:true});
export const Listing=mongoose.model('Listing',listingSchema);